// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZx1xUtHkFfuqR_oFX_BW40AvOWzrH3Ss',
    appId: '1:991811837814:android:9b917126eade18c18f2457',
    messagingSenderId: '991811837814',
    projectId: 'arcane-bus-466702-a4',
    storageBucket: 'arcane-bus-466702-a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEMK7JAD6VbnxbYqIzGqBTEmVliqqvQ2s',
    appId: '1:991811837814:ios:da9ea50fae429ae28f2457',
    messagingSenderId: '991811837814',
    projectId: 'arcane-bus-466702-a4',
    storageBucket: 'arcane-bus-466702-a4.firebasestorage.app',
    androidClientId: '991811837814-dvt43epsm72m32il4ut9rp7vcdjkppul.apps.googleusercontent.com',
    iosClientId: '991811837814-0ubnusi8dmje8o6l69jl9gkdlq2gjb5r.apps.googleusercontent.com',
    iosBundleId: 'com.example.pixHuntProject',
  );

}